spring.application.name: hello-app

info.app.name: hello
info.app.version: "${version ?:'unknown'}"


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5


whatservice.name: 'what-service'
whoservice.name: 'who-service'

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always

logging:
  level:
    nuwestlin.microservices.hello.hello: DEBUG
    #org.springframework.cloud.netflix.ribbon: DEBUG
    #com.netflix.discovery: DEBUG
    #org.springframework.cloud.openfeign: DEBUG
    #logging.level.com.netflix.eureka: trace
    #logging.level.com.netflix.discovery: trace