spring.application.name: who-service
server.port: 9000

info.app.name: who-service
info.app.version: "${version ?:'unknown'}"

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5
