spring.application.name: what-service
server.port: 8000

management:
  endpoints.web.exposure.include: "*"
  endpoint.health.show-details: always


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5